# Generated by Django 3.0.5 on 2020-04-25 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zsolozsma', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeventschedule',
            name='event',
        ),
        migrations.RemoveField(
            model_name='event',
            name='description',
        ),
        migrations.RemoveField(
            model_name='event',
            name='times',
        ),
        migrations.RemoveField(
            model_name='event',
            name='youtube_channel',
        ),
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Dátum (egyedi alkalomnál)'),
        ),
        migrations.AddField(
            model_name='event',
            name='day_of_week',
            field=models.IntegerField(blank=True, choices=[(0, 'Hétfő'), (1, 'Kedd'), (2, 'Szerda'), (3, 'Csütörtök'), (4, 'Péntek'), (5, 'Szombat'), (6, 'Vasárnap')], null=True, verbose_name='Hét napja'),
        ),
        migrations.AddField(
            model_name='event',
            name='text_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='Egyedi szöveg URL'),
        ),
        migrations.AddField(
            model_name='event',
            name='time',
            field=models.TimeField(blank=True, null=True, verbose_name='Kezdés ideje'),
        ),
        migrations.AddField(
            model_name='location',
            name='video_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='URL a közvetítéshez'),
        ),
        migrations.AddField(
            model_name='location',
            name='youtube_channel',
            field=models.CharField(blank=True, max_length=20, verbose_name='YouTube csatorna ID'),
        ),
        migrations.AlterField(
            model_name='event',
            name='video_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='Egyedi URL a közvetítéshez'),
        ),
        migrations.DeleteModel(
            name='CachedBroadcast',
        ),
        migrations.DeleteModel(
            name='CustomEventSchedule',
        ),
    ]
