# Generated by Django 3.0.5 on 2020-04-25 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zsolozsma', '0002_auto_20200425_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liturgy',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='URL részlet'),
        ),
        migrations.AlterField(
            model_name='location',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='URL részlet'),
        ),
    ]
