# Generated by Django 3.0.5 on 2020-04-26 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zsolozsma', '0003_auto_20200425_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='date',
        ),
        migrations.AddField(
            model_name='event',
            name='hash',
            field=models.CharField(null=True,blank=False, max_length=8, unique=True, verbose_name='URL hash'),
            preserve_default=False,
        ),
    ]
