# Generated by Django 3.0.5 on 2020-04-26 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zsolozsma', '0005_auto_20200426_1433'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Esemény', 'verbose_name_plural': 'Események'},
        ),
        migrations.AlterModelOptions(
            name='liturgy',
            options={'verbose_name': 'Szertartás', 'verbose_name_plural': 'Szertartások'},
        ),
        migrations.AlterModelOptions(
            name='liturgytext',
            options={'verbose_name': 'Szöveg', 'verbose_name_plural': 'Szövegek'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'Helyszín', 'verbose_name_plural': 'Helyszínek'},
        ),
    ]
