# Generated by Django 3.0.5 on 2020-04-27 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zsolozsma', '0006_auto_20200426_1449'),
    ]

    operations = [
        migrations.CreateModel(
            name='Broadcast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Dátum')),
                ('video_url', models.URLField(max_length=500, verbose_name='Videó URL')),
                ('video_iframe', models.BooleanField(blank=True, default=True, verbose_name='Videó beágyazható')),
                ('text_url', models.URLField(blank=True, max_length=500, verbose_name='Szöveg URL')),
                ('text_iframe', models.BooleanField(blank=True, default=True, verbose_name='Szöveg beágyazható')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zsolozsma.Event', verbose_name='Esemény')),
            ],
            options={
                'verbose_name': 'Közvetítés',
                'verbose_name_plural': 'Közvetítések',
            },
        ),
    ]
