# Generated by Django 3.0.5 on 2020-04-28 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zsolozsma', '0009_broadcast_video_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='duration',
            field=models.IntegerField(blank=True, null=True, verbose_name='Időtartam (perc)'),
        ),
    ]
