# Generated by Django 3.0.5 on 2020-05-04 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zsolozsma', '0010_event_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='slug',
        ),
    ]
