# Generated by Django 3.0.5 on 2020-05-04 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zsolozsma', '0011_remove_event_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='youtube_channel',
            field=models.CharField(blank=True, max_length=24, verbose_name='Egyedi YouTube csatorna ID'),
        ),
    ]
