# Generated by Django 3.0.5 on 2020-05-06 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zsolozsma', '0012_event_youtube_channel'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(blank=True, choices=[(0, 'Hétfő'), (1, 'Kedd'), (2, 'Szerda'), (3, 'Csütörtök'), (4, 'Péntek'), (5, 'Szombat'), (6, 'Vasárnap')], null=True, verbose_name='Hét napja')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='Kezdés ideje')),
                ('youtube_channel', models.CharField(blank=True, max_length=24, verbose_name='Egyedi YouTube csatorna ID')),
                ('video_url', models.URLField(blank=True, max_length=500, verbose_name='Egyedi URL a közvetítéshez')),
                ('text_url', models.URLField(blank=True, max_length=500, verbose_name='Egyedi szöveg URL')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zsolozsma.Event', verbose_name='Esemény')),
            ],
            options={
                'verbose_name': 'Esemény időpont',
                'verbose_name_plural': 'Esemény időpontok',
            },
        ),
    ]
