# Generated by Django 3.0.5 on 2020-05-06 16:47
from django.db import migrations
import secrets

def copy_schedule(apps, schema_editor):
    Event = apps.get_model('zsolozsma', 'Event')
    EventSchedule = apps.get_model('zsolozsma', 'EventSchedule')

    events_dict = {}

    for event in Event.objects.all():

        schedule = EventSchedule()
        schedule.day_of_week = event.day_of_week
        schedule.time = event.time
        schedule.hash = secrets.token_hex(4)
        # URL-eket nem másolunk, még nincs napi egyedi érték sehol

        key = (event.location, event.liturgy)
        if key in events_dict:
            key_event = events_dict[key]
            event.delete()
        else:
            event.save()

            key_event = event
            events_dict[key] = key_event

        schedule.event = key_event

        schedule.save()


class Migration(migrations.Migration):

    dependencies = [
        ('zsolozsma', '0013_eventschedule'),
    ]

    operations = [
        migrations.RunPython(copy_schedule)
    ]
