# Generated by Django 3.0.5 on 2020-05-06 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zsolozsma', '0014_auto_20200506_1847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='day_of_week',
        ),
        migrations.RemoveField(
            model_name='event',
            name='time',
        ),
    ]
