# Generated by Django 3.0.5 on 2020-05-06 17:25

from django.db import migrations

def delete_broadcasts(apps, schema_editor):    
    Broadcast = apps.get_model('zsolozsma', 'Broadcast')

    Broadcast.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('zsolozsma', '0015_auto_20200506_1908'),
    ]

    operations = [
        migrations.RunPython(delete_broadcasts)
    ]
