# Generated by Django 3.0.5 on 2020-11-13 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zsolozsma', '0019_auto_20201112_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='fullname',
            field=models.CharField(max_length=300, verbose_name='Teljes név'),
        ),
        migrations.AlterField(
            model_name='location',
            name='slug',
            field=models.SlugField(verbose_name='URL részlet'),
        ),
    ]
