# Generated by Django 3.0.5 on 2020-11-14 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zsolozsma', '0020_auto_20201113_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='liturgy',
            name='text_url_pattern',
            field=models.CharField(blank=True, max_length=300, verbose_name='Szöveg URL sablon'),
        ),
    ]
