# Generated by Django 3.0.5 on 2020-12-13 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zsolozsma', '0023_auto_20201210_0823'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='denomination',
            options={'verbose_name': 'Felekezet/rítus', 'verbose_name_plural': 'Felekezetek/rítusok'},
        ),
        migrations.AddField(
            model_name='eventschedule',
            name='valid_from',
            field=models.DateField(blank=True, null=True, verbose_name='Érvényesség kezdete'),
        ),
        migrations.AddField(
            model_name='eventschedule',
            name='valid_to',
            field=models.DateField(blank=True, null=True, verbose_name='Érvényesség vége'),
        ),
    ]
