# Generated by Django 3.0.5 on 2021-02-16 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zsolozsma', '0024_auto_20201213_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='miserend_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='miserend.hu ID'),
        ),
    ]
