# Generated by Django 3.0.5 on 2021-03-07 11:47

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('zsolozsma', '0025_location_miserend_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='liturgy',
            name='text',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Szöveg'),
        ),
        migrations.AlterField(
            model_name='event',
            name='duration',
            field=models.IntegerField(blank=True, help_text='Csak akkor kell kitölteni, ha eltér a szokásostól.', null=True, verbose_name='Időtartam (perc)'),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Vedd ki a pipát, ha az esemény határozatlan ideig szünetel.', verbose_name='Aktív'),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(help_text='A szertartás neve az adott helyen, ez fog megjelenni a listákban.', max_length=100, verbose_name='Név'),
        ),
        migrations.AlterField(
            model_name='event',
            name='text_url',
            field=models.URLField(blank=True, help_text='Csak akkor kell kitölteni, ha más, mint a szertartás aznapi szokásos szövege.', max_length=500, verbose_name='Egyedi szöveg URL'),
        ),
        migrations.AlterField(
            model_name='event',
            name='video_url',
            field=models.URLField(blank=True, help_text='Csak akkor kell kitölteni, ha más, mint a helyszín szokásos közvetítési oldala.', max_length=500, verbose_name='Egyedi URL a közvetítéshez'),
        ),
        migrations.AlterField(
            model_name='event',
            name='youtube_channel',
            field=models.CharField(blank=True, help_text='Csak akkor kell kitölteni, ha más, mint a helyszín szokásos csatornája.', max_length=24, verbose_name='Egyedi YouTube csatorna ID'),
        ),
        migrations.AlterField(
            model_name='eventschedule',
            name='text_url',
            field=models.URLField(blank=True, help_text='Ha más, mint a szertartás aznapi szokásos szövege.', max_length=500, verbose_name='Egyedi szöveg URL'),
        ),
        migrations.AlterField(
            model_name='eventschedule',
            name='video_url',
            field=models.URLField(blank=True, help_text='Ha más, mint a helyszín szokásos közvetítési oldala.', max_length=500, verbose_name='Egyedi URL a közvetítéshez'),
        ),
        migrations.AlterField(
            model_name='eventschedule',
            name='youtube_channel',
            field=models.CharField(blank=True, help_text='Ha más, mint az esemény szokásos csatornája.', max_length=24, verbose_name='Egyedi YouTube csatorna ID'),
        ),
        migrations.AlterField(
            model_name='liturgy',
            name='text_url_pattern',
            field=models.CharField(blank=True, help_text='Link a szertartás szövegeihez, lehet benne <a href="https://strftime.org/">dátumformátum.</a>', max_length=300, verbose_name='Szöveg URL sablon'),
        ),
        migrations.AlterField(
            model_name='location',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Vedd ki a pipát, ha a helyszínen nincsenek közvetítések.', verbose_name='Aktív'),
        ),
        migrations.AlterField(
            model_name='location',
            name='miserend_id',
            field=models.IntegerField(blank=True, help_text='A helyszín azonosítója a miserend.hu-n. Ha megadod, ott is megjelennek a közvetítések.', null=True, verbose_name='miserend.hu ID'),
        ),
    ]
