# Generated by Django 3.1.7 on 2021-03-09 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zsolozsma', '0026_auto_20210307_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='last_checked',
            field=models.DateField(blank=True, null=True, verbose_name='Utoljára ellenőrizve'),
        ),
    ]
