# Generated by Django 3.1.7 on 2021-03-12 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zsolozsma', '0027_location_last_checked'),
    ]

    operations = [
        migrations.AddField(
            model_name='liturgy',
            name='duration',
            field=models.IntegerField(help_text='Szokásos időtartam, egyes helyszíneken lehet eltérő.', null=True, verbose_name='Időtartam (perc)'),
        ),
    ]
