# Generated by Django 3.1.7 on 2021-03-13 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zsolozsma', '0028_liturgy_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liturgy',
            name='duration',
            field=models.IntegerField(default=60, help_text='Szokásos időtartam, egyes helyszíneken lehet eltérő.', verbose_name='Időtartam (perc)'),
        ),
    ]
