# Generated by Django 3.1.7 on 2021-03-16 07:17

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('zsolozsma', '0029_auto_20210313_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liturgy',
            name='description',
            field=tinymce.models.HTMLField(blank=True, max_length=500, verbose_name='Leírás'),
        ),
    ]
