# Generated by Django 3.1.7 on 2021-03-16 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zsolozsma', '0031_auto_20210316_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventschedule',
            name='is_extraordinary',
            field=models.BooleanField(default=False, help_text='Jelöld be, ha ez az esemény felülírja az aznapi miserendet.', verbose_name='Rendkívüli esemény'),
        ),
    ]
