# Generated by Django 3.1.7 on 2021-03-20 15:13

from django.db import migrations


def schedules_to_events(apps, schema_editor):
    EventSchedule = apps.get_model('zsolozsma', 'EventSchedule')

    for schedule in EventSchedule.objects.all():
        event = schedule.event

        schedule.location = event.location
        schedule.liturgy = event.liturgy
        schedule.duration = event.duration

        if (event.name != event.liturgy.name):
            schedule.name = event.name

        schedule.save()


class Migration(migrations.Migration):

    dependencies = [
        ('zsolozsma', '0033_auto_20210320_1557'),
    ]

    operations = [migrations.RunPython(schedules_to_events)]
