# Generated by Django 3.1.7 on 2021-03-20 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zsolozsma', '0034_schedule_to_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventschedule',
            name='event',
        ),
        migrations.AlterField(
            model_name='eventschedule',
            name='liturgy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zsolozsma.liturgy', verbose_name='Szertartás'),
        ),
        migrations.AlterField(
            model_name='eventschedule',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zsolozsma.location', verbose_name='Helyszín'),
        ),
        migrations.AlterField(
            model_name='eventschedule',
            name='name',
            field=models.CharField(blank=True, help_text='A szertartás neve az adott helyen, ez fog megjelenni a listákban.', max_length=100, null=True, verbose_name='Név'),
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]


# select
# 	e.id,
# 	e.hash,
# 	e.location_id,
# 	e.liturgy_id,
# 	e.name,
# 	e.duration,
# 	e.youtube_channel,
# 	e.video_url,
# 	e.text_url,
# 	e.day_of_week,
# 	e.time	
# from zsolozsma_eventschedule e
# order by e.id
